version: "3.7"
services:
  sample-project-server:
    image: c6oio/sample-project-server:$USER
    build:
      context: ./sample-project-server
  sample-project-sockets:
    image: c6oio/sample-project-sockets:$USER
    build:
      context: ./sample-project-sockets
  sample-project-web:
    image: c6oio/sample-project-web:$USER
    build:
      context: ./sample-project-web
