apiVersion: v1

kind: Service

metadata:
  name: halyard-frontend-service
  labels:
    app: halyard-frontend-service
    
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: halyard-frontend-pod
    