apiVersion: v1

kind: Service

metadata:
  name: halyard-backend-service
  labels:
    app: halyard-backend-service
    
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: halyard-backend-pod
