apiVersion: apps/v1

kind: Deployment

metadata:
  name: halyard-backend
  labels:
    app: halyard
    component: backend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: halyard
      component: backend

  template:
    metadata:
      labels:
        app: halyard
        component: backend

    spec:
      containers:
        - name: halyard-backend
          image: robblovell/halyard-backend:1.3
          imagePullPolicy: Always
          env:
            - name: HALYARD_ECHO
              value: halyard-echo:8080
            - name: HALYARD_DATABASE
              value: mongodb://halyard-database:27017
          ports:
            - containerPort: 3000