apiVersion: apps/v1

kind: Deployment

metadata:
  name: halyard-database-deployment
  labels:
    app: halyard-database-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: halyard-database-pod

  template:
    metadata:
      name: halyard-database-pod
      labels:
        app: halyard-database-pod

    spec:
      containers:
        - name: mongodb-container
          image: mongo
          env: 
            - name: MONGO_INITDB_DATABASE
              value: halyard-database
          ports:
            - containerPort: 27017 