apiVersion: v1
kind: Service
metadata:
  name: halyard-backend
  labels:
    app: halyard
    component: backend
spec:
  type: NodePort
  ports:
    - name: unsecure
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: halyard
    component: backend