apiVersion: apps/v1

kind: Deployment

metadata:
  name: halyard-frontend
  labels:
    app: halyard
    component: frontend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: halyard
      component: frontend

  template:
    metadata:
      labels:
        app: halyard
        component: frontend
    spec:
      containers:
        - name: halyard-frontend
          image: robblovell/halyard-frontend:1.3
          imagePullPolicy: Always
          env:
            - name: HALYARD_API_HOST
              value: halyard-backend
            - name: HALYARD_API_PORT
              value: '3000'
          ports:
            - containerPort: 80