apiVersion: v1

kind: Service

metadata:
  name: halyard-database-service
  labels:
    app: halyard-database-service
    
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: halyard-database-pod
    