apiVersion: apps/v1

kind: Deployment

metadata:
  name: sample-project-sockets
  labels:
    app: sample-project
    component: sockets

spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-project
      component: sockets

  template:
    metadata:
      labels:
        app: sample-project
        component: sockets

    spec:
      containers:
        - name: sample-project-sockets
          image: c6oio/sample-project-sockets:latest
          imagePullPolicy: Always
          env:
            - name: SAMPLE_PROJECT_SOCKETS_PORT
              value: '8999'
          ports:
            - containerPort: 8999