apiVersion: v1
kind: Service
metadata:
  name: sample-project-sockets
  labels:
    app: sample-project
    component: sockets
spec:
  ports:
    - protocol: TCP
      port: 8999
      targetPort: 8999
  selector:
    app: sample-project
    component: sockets