apiVersion: v1
kind: Service
metadata:
  name: sample-project-database
  labels:
    app: sample-project
    component: database
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: sample-project
    component: database