apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-project-server
  labels:
    app: sample-project
    component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-project
      component: server
  template:
    metadata:
      labels:
        app: sample-project
        component: server
    spec:
      containers:
        - name: sample-project-server
          image: c6oio/sample-project-server:latest
          imagePullPolicy: Always
          env:
            - name: SAMPLE_PROJECT_ECHO
              value: http://sample-project-echo:8080
            - name: SAMPLE_PROJECT_DATABASE
              value: mongodb://sample-project-database:27017/sample-project-database
          envFrom:
            - configMapRef:
                name: sample-project-server-config
          ports:
            - containerPort: 3000