apiVersion: system.codezero.io/v1
kind: App
name: halyard-frontend
appId:  halyard-frontend
package: '@provisioner/appengine'
icon: icon.svg
editions:
  - name: stable
    status: private
    spec:
      routes:
        - type: http
          targetService: halyard-frontend
      provisioner:
        package: '@provisioner/appengine'
        tag-prefix: appengine
        image: 'robblovell/halyard-frontend:1.1'
        ports: 80
        configs:
          HALYARD_APIHOST: halyard-backend
          HALYARD_APIPORT: 3000
      marina:
        launch:
          type: inline
          popUp: true
