apiVersion: system.codezero.io/v1
kind: App
name: sample-project-database
appId: sample-project-database
package: '@provisioner/appengine'
editions:
  - name: stable
    status: private
    spec:
      routes:
        - type: http
          targetService: sample-project-database
      provisioner:
        tag-prefix: appengine
        package: '@provisioner/appengine'
        image: 'mongo:4.4.5'
        ports: 27017
#        env:
#          - name: MONGO_INITDB_DATABASE
#            value: sample-project-database
        config:
        - sample-project-database:
            user: testUser
            password: password
            roles:
              - readWrite
            secretKey: SAMPLE_PROJECT_DATABASE
            secretKeyRef:
              name: mariadb-root
              key: {{rootPasswordKey}}
      marina:
        launch:
          type: inline
          popUp: false