apiVersion: system.codezero.io/v1
kind: Environment
metadata:
  name: front-end-dev
spec:
  services:
    sample-project-database:
      fromFile: ../apps/sample-project-database.yaml
    sample-project-echo:
      fromFile: ../apps/sample-project-echo.yaml
      await: sample-project-database
    sample-project-server:
      fromFile: ../apps/sample-project-server.yaml
      await: sample-project-echo
    sample-project-web: local