
apiVersion: system.codezero.io/v1
kind: Environment
metadata:
  name: front-end-dev
spec:
  services:
    database:
      fromFile: ../apps/database.yaml
    backend:
      fromFile: ../apps/backend.yaml
      await: database