
apiVersion: system.codezero.io/v1
kind: Environment
metadata:
  name: prod
spec:
  services:
    database:
      secretsRef:
      - mongo-connections
    backend: ../apps/backend.yaml
    frontend: ../apps/frontend.yaml
