
apiVersion: system.codezero.io/v1
kind: Environment
metadata:
  name: prod
spec:
  services:
    sample-project-database:
      fromConnectionString: "mongodb://sample-project-database:27017"
      fromIAMToken: sample-project-database-IAM-access
      fromCredentials: sample-project-database-credentials
      fromSecret: sample-project-database-secret
      fromConfig: sample-project-database-config
      fromContainer: 'mongo:4.4.5'
        connection: 'alksdfjaldfsjalkdfjaldfjalsdfjlaksdfjlaksdfjlaksdfjlkjalkfsdj'
      fromFile: '../apps/sample-project-database.yaml'

    sample-project-echo:
      fromRepo: git@github.com:robblovell/echo-server.git
      fromContainer: 'robblovell/echo-server:2.2'
      fromFile: '../apps/sample-project-echo.yaml'

    sample-project-server:
      fromFile: ../apps/sample-project-server.yaml
      await: [ sample-project-echo, sample-project-database ]

    sample-project-web:
      fromFile: ../apps/sample-project-web.yaml
      await: sample-project-server

    halyard_wikijs:
      fromContainer: 'wikijs:3.5.6'
        CONNECTION_TO_DATABASE: sample-project-database
        PORT:
        HOST:
