apiVersion: system.codezero.io/v1
kind: Environment
metadata:
  name: dev # this defines the namespace created for this environment.
spec:
  services:
    # each service makes available to the environment provisioner a connection string.
    sample-project-database:
      fromFile: ../apps/sample-project-database.yaml

    sample-project-echo:
      fromFile: ../apps/sample-project-echo.yaml

    sample-project-server:
      fromFile: ../apps/sample-project-server.yaml
      # Dependencies -> Option 2: optionally, you can specify what the dependencies are here instead of in the environment.
      dependsOn: [ sample-project-echo, sample-project-database ]

      # Initializers -> Option 2: This initializer is defined here in the environment for the service that needs it and gets passed to the database provisioner
      initializers:
        - target: sample-project-database
          action:
            name: MONGO_INITDB_DATABASE # this is a command to the provisioner
            value: sample-project-database
            config:
              user: testUser
              password: password
              roles: readWrite
              secretKey: SAMPLE_PROJECT_DATABASE_DATABASE

    sample-project-web:
      fromFile: ../apps/sample-project-web.yaml
      dependsOn: sample-project-server
