apiVersion: system.codezero.io/v1
kind: App
name: sample-project-mongo
appId: sample-project-mongo
package: '@provisioner/appengine'
editions:
  - name: stable
    status: private
    spec:
      # Routes is strictly not necessary, don't need public visiblity
      routes:
        - type: http
          targetService: sample-project-database

      provisioner:
        name: mongo
        tag: 4.4.5
        rootUser: root
        storageClass: do-block-storage
#        secretKeyRef: sample-project-mongo
        config:
          - sample-project-mongo:
              user: testUser
              password: password
              roles:
                - readWrite
              secretKey: SAMPLE_PROJECT_DATABASE