apiVersion: system.codezero.io/v1
kind: App
name: sample-project-web
appId: sample-project-web
package: '@provisioner/appengine'
icon: icon.svg
editions:
  - name: stable
    status: private
    spec:
      routes:
        - type: http
          targetService: sample-project-web
      provisioner:
        package: '@provisioner/appengine'
        tag-prefix: appengine
        image: 'robblovell/sample-project-web:1.2'
        ports: 80
        configs:
          SAMPLE_PROJECT_API_HOST: SAMPLE_PROJECT_SERVER_HOSTNAME
          SAMPLE_PROJECT_API_PORT: SAMPLE_PROJECT_SERVER_PORT
        secretRefs:
          - sample-project-server
          # Brings in stuff the sample-project services created for me to get to it:
          # SAMPLE_PROJECT_SERVER
          # SAMPLE_PROJECT_SERVER_HOST
          # SAMPLE_PROJECT_SERVER_HOSTNAME
          # SAMPLE_PROJECT_SERVER_HREF
          # SAMPLE_PROJECT_SERVER_ORIGIN
          # SAMPLE_PROJECT_SERVER_PASSWORD
          # SAMPLE_PROJECT_SERVER_PORT
          # SAMPLE_PROJECT_SERVER_PROTOCOL
          # SAMPLE_PROJECT_SERVER_USERNAME

      marina:
        launch:
          type: inline
          popUp: true