apiVersion: system.codezero.io/v1
kind: App
name: sample-project-server
appId: sample-project-server
package: '@provisioner/appengine'
icon: icon.svg
editions:
  - name: stable
    status: private
    spec:
      # this gets me a route to the outside world.
      routes:
        - type: http
          targetService: sample-project-server

      provisioner:
        package: '@provisioner/appengine'
        tag-prefix: appengine
        image: 'robblovell/sample-project-server:1.2'
        ports: 3000
        exports: # Exports -> Option 1: The environment provisioner does this for me
          # Exports -> Option 2: The connection string is explicitly given here
          SAMPLE_PROJECT_SERVER: "http://sample-project-server:80"

        # Secrets -> Option 1: Reference other services secrets files
        secretRefs:
          - sample-project-echo
          - sample-project-database

        # Config -> Option 1: This service defines connected services.
        configMaps:
          - sample-project-echo
          - sample-project-database
        # Config -> Option 1b: This service defines it's own config map (a beacon?).
        # install setup, forms the beacon
        configs:
          SAMPLE_PROJECT_DATABASE: "mongodb://sample-project-database:27017"
          SAMPLE_PROJECT_ECHO: "http://sample-project-echo:8080"

        # Dependencies -> Option 1: optionally, you can specify what the dependencies are here instead of in the environment.
        dependsOn: [ sample-project-echo, sample-project-database ]

        # XXX Initializers -> Option 1: This initializer is defined here by the service that needs it and gets passed to the database provisioner
        initializers:
          - target: sample-project-database
            action:
              name: MONGO_INITDB_DATABASE # this is a command to the provisioner
              value: sample-project-database
              config:
                user: testUser
                password: password
                roles: readWrite
                secretKey: SAMPLE_PROJECT_DATABASE_DATABASE
      marina:
        launch:
          type: inline
          popUp: false