apiVersion: system.codezero.io/v1
kind: App
name: sample-project-database
appId: sample-project-database
package: '@provisioner/appengine'
editions:
  - name: stable
    status: private
    spec:
      # Routes is strictly not necessary, don't need public visiblity
      routes:
        - type: http
          targetService: sample-project-database

      provisioner:
        tag-prefix: appengine
        package: '@provisioner/appengine'
        image: 'mongo:4.4.5'
        ports: 27017

# Idea?
#        exports: ## the environment provisioner does this for me ##
#          SAMPLE_PROJECT_DATABASE: "mongodb://sample-project-database:27017"
#          SAMPLE_PROJECT_DATABASE_HOST: "sample-project-database:27017"
#          SAMPLE_PROJECT_DATABASE_HOSTNAME: "sample-project-database"
#          SAMPLE_PROJECT_DATABASE_HREF: "mongodb://sample-project-database:27017"
#          SAMPLE_PROJECT_DATABASE_ORIGIN: "mongodb://sample-project-database"
#          SAMPLE_PROJECT_DATABASE_PASSWORD: ""
#          SAMPLE_PROJECT_DATABASE_PORT: "27017"
#          SAMPLE_PROJECT_DATABASE_PROTOCOL: "mongodb://"
#          SAMPLE_PROJECT_DATABASE_USERNAME: ""
#          # the initialzer
#          SAMPLE_PROJECT_DATABASE_DATABASE: "mongodb://testUser:password@sample-project-database:27017/sample-project-database"
#          # ... more breakdowns of SAMPLE_PROJECT_DATABASE_DATABASE

        # Instructions to the provisioner on how to initialize this service.
        # Should this be in the service that needs it? What if multiple services need it?
        # Initializers -> Option 3: This initializer is defined here with the target of the initializer and gets passed to the database provisioner
        initializers: # Self initialize, contextual to the environment
          - target: sample-project-database
            action:
              name: MONGO_INITDB_DATABASE # this is a command to the provisioner
              value: sample-project-database
              config:
                user: testUser
                password: password
                roles: readWrite
                secretKey: SAMPLE_PROJECT_DATABASE_DATABASE
      marina:
        launch:
          type: inline
          popUp: false