name: publish
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Log in to registry
        run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and publish
        run: |
          export USER=$(echo $GITHUB_SHA | cut -c 1-7)
          docker-compose build
          docker-compose push
          docker images | grep c6o | awk '{ print $1 }' | xargs -I{} docker tag {}:$USER {}:latest
          export USER=latest
          docker-compose push